# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pdf_parser_pb2 as pdf__parser__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pdf_parser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PDFParserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessPDF = channel.unary_unary(
                '/pdfparser.PDFParserService/ProcessPDF',
                request_serializer=pdf__parser__pb2.PDFRequest.SerializeToString,
                response_deserializer=pdf__parser__pb2.PDFResponse.FromString,
                _registered_method=True)


class PDFParserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessPDF(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PDFParserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessPDF': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPDF,
                    request_deserializer=pdf__parser__pb2.PDFRequest.FromString,
                    response_serializer=pdf__parser__pb2.PDFResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pdfparser.PDFParserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pdfparser.PDFParserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PDFParserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessPDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdfparser.PDFParserService/ProcessPDF',
            pdf__parser__pb2.PDFRequest.SerializeToString,
            pdf__parser__pb2.PDFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
