# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdf_parser.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pdf_parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pdf_parser.proto\x12\tpdfparser\"\x1e\n\nPDFRequest\x12\x10\n\x08pdf_path\x18\x01 \x01(\t\"1\n\x0bPDFResponse\x12\x12\n\ntotal_time\x18\x01 \x01(\x01\x12\x0e\n\x06result\x18\x02 \x01(\t2O\n\x10PDFParserService\x12;\n\nProcessPDF\x12\x15.pdfparser.PDFRequest\x1a\x16.pdfparser.PDFResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pdf_parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PDFREQUEST']._serialized_start=31
  _globals['_PDFREQUEST']._serialized_end=61
  _globals['_PDFRESPONSE']._serialized_start=63
  _globals['_PDFRESPONSE']._serialized_end=112
  _globals['_PDFPARSERSERVICE']._serialized_start=114
  _globals['_PDFPARSERSERVICE']._serialized_end=193
# @@protoc_insertion_point(module_scope)
